version: '2.2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.3
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    expose:
      - 9200
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.2.3
    links:
      - elasticsearch
    ports:
      - 5601:5601
  proxy:
    image: nginx-proxy
    ports:
      - 8080:80
    links:
      - kibana
